name: Deploy

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0

      - name: Deploy site
        uses: ad-m/github-push-action@master
        run: |
          git config --local user.email "no-reply@cindy.kim"
          git config --local user.name "Deploy bot"
          npm install && npm run deploy
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
