name: Deploy

on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [contentful-updated]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages and build
        run:
          echo "GETFORM_KEY=$GETFORM_KEY"
          # npm ci
          # npm run build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          GETFORM_KEY: ${{ secrets.GETFORM_KEY }}
          NODE_ENV: production
      # - name: Push to master
      #   uses: peaceiris/actions-gh-pages@v3.5.7
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     publish_branch: master
      #     cname: cindy.kim
      #     allow_empty_commit: true
      #     force_orphan: true
